routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/testing', function(){

    return "This is a testing route";


});
Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
Route::resource('roles', 'RoleController');
Route::get('/exists/{file}' , function($file){

    if(Storage::disk('public')->exists('Basic/branch')){

        return "File exists";
    }
    else{
        return "No such file";
    }

});



Route::resource('participants', 'ParticipantController');

Route::get('/upload', 'UserController@uploadPhoto')->name('upload.image');
Route::post('/uploadResult', 'UserController@upload')->name('upload.result');


Route::get('locale/{locale}', function($locale){
            Session::put('locale', $locale);
            return redirect()->back();
})->name('locale');


Route::get('/home', 'HomeController@index')->name('home');



    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

Route::resource('users', 'UserController');


Route::group(['middleware' => ['auth']], function () {


    //

    Route::group(['middleware' => ['permission:user-manage-roles']], function () {
        //

//        Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
//        Route::resource('roles', 'RoleController');

    });

    Route::group(['middleware' => ['permission:user-manage-users']], function () {


        //        Route::resource('users', 'UserController');

    });

    Route::group(['middleware' => ['permission:article-manage-articles']], function () {
        //
        Route::post('articles/image_upload', 'ArticleController@upload')->name('upload');
        Route::get('articles/translate', 'ArticleController@translate')->name('translate');
        Route::get('articles/filter', 'ArticleController@filter')->name('articles.filter');
        Route::get('articles/change-status/{article}', 'ArticleController@changeStatus')->name('articles.changestatus');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('articles', 'ArticleController');
    });

    Route::group(['middleware' => ['permission:article-manage-categories']], function () {
        //
        Route::get('article-category/subcategories/{category}', 'ArticleCategoryController@listSubcategories')->name('article-category.subcategories');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('article-category', 'ArticleCategoryController');
    });

    Route::group(['middleware' => ['permission:article-manage-categories']], function () {
        //
        Route::get('article-category/subcategories/{category}', 'ArticleCategoryController@listSubcategories')->name('article-category.subcategories');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('article-category', 'ArticleCategoryController');
    });

    Route::group(['middleware' => ['permission:translation-manage-translations']], function () {

        // Route to translation manager interface : /translations
        // The middleware to control translation manager is written in app/config/translation-manager.php
        // Refer github  https://github.com/barryvdh/laravel-translation-manager

    });
    Route::group(['middleware' => ['permission:media-manage-media']], function () {
//        ctf0\MediaManager\MediaRoutes::routes();
    });
//    ctf0\MediaManager\MediaRoutes::routes();


});

ctf0\MediaManager\MediaRoutes::routes();
//Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
//Route::resource('roles', 'RoleController');
////





// MediaManager

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
    //
    protected $fillable =[

        'name',
        'prize'

    ];
}

app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use App\Participant;
use App\User;
use Illuminate\Http\Request;

class ParticipantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

       $participants = Participant::all();

       return view('participants.index', ['participants' => $participants]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('participants.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $participant = new Participant();
        $participant->name = $request->input('name');
        $participant->prize = 0;
        $participant->save();
        $request->session()->flash('status-green', 'New participant "' . $request->input('name') . '"" has been created.');
        return redirect(route('participants.create'));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    public function luckydraw(Request $request)
    {
        //
//        $request->session()->flash('status-green', 'Hello!');

        return view('participants.luckydraw');
    }

    public function draw(Request $request)
    {
        //
        sleep(4);
        $participants = Participant::where('prize', '0')->get();
//        return count($participants);
        $number = rand(0, count($participants));
        $participants[$number]->prize = -1;
        $participants[$number]->save();
        $request->session()->flash('status-green', 'The winner is ' .  $participants[$number]->name . '. Congratulations! .');
//            return $participants[$number]->prize;
//            return $number;
        return redirect(route('participants.luckydraw'));


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request , $id)
    {
        //
        $participant = Participant::find($id);
        $participant->delete();
        $request->session()->flash('status-red', 'The winner is ' .  $participant->name . ' has been deleted .');
        return redirect(route('participants.index'));

    }
}

resources/views/participants/create.blade.php
@extends('layouts.app2')

@section('content')

    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create a new participant') }}

                        <a href="{{ route('participants.index')}}" class="btn btn-outline-primary btn-space float-right">Participant List</a>

                    </div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('participants.store') }}" autocomplete="off">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="" required>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>

                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-outline-success">
                                        {{ __('Create') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/participants/index.blade.php
@extends('layouts.app2')


@section('content')
    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif
    <div class="container">
        {{--        <div class="row justify-content-center">--}}

        <div class="">
            <div class="card">
                <div class="card-header">
                    List of Participants
                    <a href="{{ route('participants.create') }}" class="float-right btn btn-success btn-space" >Create new participants</a>
                    <a href="{{ route('participants.luckydraw') }}" class="float-right btn btn-dark btn-space" >Lucky draw</a>
                </div>

                <div>
                    <table class="article-category-list">
                        <tr>

                            <th>Username</th>
                            <th>Prize</th>



                        </tr>
                        @foreach ($participants as $participant)
                            <tr>

                                {{--                                <th><img src="{{ $user->photo? $user->photo : asset('storage/Basic/profile-placeholder.png')  }}" class="img-thumbnail rounded" width="50" height="50"></th>--}}
{{--                                <th><img src="{{$user->photo? asset('storage/uploads/user/profile/'. $user->photo) : asset('storage/Basic/profile-placeholder.png') }}" alt="" width="50" height="50" ></th>--}}
{{--                                <td>{{$user->id}}</td>--}}
                                <td>{{$participant->name}}</td>
{{--                                <td>{{$user->email}}</td>--}}

{{--                                <td>{{empty($user->getRoleNames()[0])? '-' : $user->getRoleNames()[0]}}</td>--}}
                                <td>{{$participant->prize}}</td>

{{--                                <td><a href="#" class="btn btn-outline-primary btn-space">Edit</a></td>--}}
{{--                                <td><a href="{{ route('users.edit', [ 'participant' => $participant->id])}}" class="btn btn-outline-primary btn-space">Edit</a></td>--}}

                                <td>
                                    <form method="post" action="{{ route('participants.destroy', [ $participant->id]) }}">
                                        @csrf @method('delete')

                                        <div class="control">
                                            <button type="submit" class="btn btn-outline-danger btn-space" onclick="return confirm('Are you sure you want to delete this participant?')">
                                                Delete
                                            </button>
                                        </div>

                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/participants/luckydraw.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Laravel</title>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 60px;
        }

        .links > a {
            /*color: #636b6f;*/
            /*padding: 0 25px;*/
            padding: 3 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }

        .standout{
            background-size: 200px;
        }
    </style>
</head>
<body>



{{--    <div id="c1">--}}
{{--        <welcomee :title="'This cool App'"></welcomee>--}}
{{--    </div>--}}
{{--    <script type="text/javascript" src="js/app.js"></script>--}}
<div class="flex-center position-ref full-height">


{{--    @if (Route::has('login'))--}}
{{--        <div class="top-right links">--}}

{{--        <div class="nav-link" aria-labelledby="navbarDropdown">--}}
{{--            <a class="dropdown-item" href="{{ route('logout') }}"--}}
{{--               onclick="event.preventDefault();--}}
{{--        document.getElementById('logout-form').submit();">--}}
{{--                {{ trans('g.Logout') }}--}}
{{--            </a>--}}

{{--            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
{{--                @csrf--}}
{{--            </form>--}}
{{--        </div>--}}

{{--            <a class="nav-link" href="{{route('locale', ['locale' => 'en'])}}">EN</a>--}}
{{--            <a class="nav-link" href="{{route('locale', ['locale' => 'cn'])}}">中文</a>--}}
{{--            <a class="nav-link" href="{{route('locale', ['locale' => 'my'])}}">B.Malaysia</a>--}}

{{--            @auth--}}
{{--                <a href="{{ route('home') }}">{{trans('g.Home')}}</a>--}}
{{--            @else--}}
{{--                <a href="{{ route('login') }}">{{trans('g.Login')}}</a>--}}
{{--                @if (Route::has('register'))--}}
{{--                    <a href="{{ route('register') }}">{{trans('g.Register')}}</a>--}}
{{--                @endif--}}
{{--            @endauth--}}
{{--        </div>--}}
{{--    @endif--}}

    <div class="content">
        @if (session('status-green'))
            <div class="alert alert-success standout">
                {{ session('status-green') }}
            </div>

        @elseif(session('status-red'))
            <div class="alert alert-danger standout">
                {{ session('status-red') }}
            </div>

        @elseif(session('status-yellow'))
            <div class="alert alert-warning standout">
                {{ session('status-yellow') }}
            </div>
        @endif
        <div class="title m-b-md">
          PFSKL

                <img src="{{asset('storage/pfslogo.jpg')}}" style="width:700px;height:auto;">


        </div>

        <div class="links">
            <a href="{{ route('participants.index')}}" class="btn btn-primary btn-space float-right">Participant List</a>
            <a href="{{ route('participants.draw')}}" class="btn btn-success btn-space float-right">Lucky Draw</a>
            <a href="{{ route('participants.luckydraw')}}" class="btn btn-dark btn-space float-right">Refresh</a>

{{--            <a href="{{route('articles.index')}}">{{trans('g.Articles')}}</a>--}}
{{--            <a href="{{route('users.index')}}">{{trans('g.Users')}}</a>--}}
{{--            <a href="{{route('roles.index')}}">{{trans('g.Roles')}}</a>--}}
{{--            <a href="/translations">{{trans('g.Translation')}}</a>--}}
{{--            <a href="/media">{{trans('g.Media')}}</a>--}}
            {{--                    <a href="/media">{{trans('g.Media')}}</a>--}}
            {{--                    <a href="/media">{{trans('g.Media')}}</a>--}}

        </div>
    </div>
</div>
</body>
</html>