routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/testing', function(){

    return "This is a testing route";


});
Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
Route::resource('roles', 'RoleController');
Route::get('/exists/{file}' , function($file){

    if(Storage::disk('public')->exists('Basic/branch')){

        return "File exists";
    }
    else{
        return "No such file";
    }

});



Route::resource('participants', 'ParticipantController');

Route::get('/upload', 'UserController@uploadPhoto')->name('upload.image');
Route::post('/uploadResult', 'UserController@upload')->name('upload.result');


Route::get('locale/{locale}', function($locale){
            Session::put('locale', $locale);
            return redirect()->back();
})->name('locale');


Route::get('/home', 'HomeController@index')->name('home');



    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

Route::resource('users', 'UserController');


Route::group(['middleware' => ['auth']], function () {


    //

    Route::group(['middleware' => ['permission:user-manage-roles']], function () {
        //

//        Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
//        Route::resource('roles', 'RoleController');

    });

    Route::group(['middleware' => ['permission:user-manage-users']], function () {


        //        Route::resource('users', 'UserController');

    });

    Route::group(['middleware' => ['permission:article-manage-articles']], function () {
        //
        Route::post('articles/image_upload', 'ArticleController@upload')->name('upload');
        Route::get('articles/translate', 'ArticleController@translate')->name('translate');
        Route::get('articles/filter', 'ArticleController@filter')->name('articles.filter');
        Route::get('articles/change-status/{article}', 'ArticleController@changeStatus')->name('articles.changestatus');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('articles', 'ArticleController');
    });

    Route::group(['middleware' => ['permission:article-manage-categories']], function () {
        //
        Route::get('article-category/subcategories/{category}', 'ArticleCategoryController@listSubcategories')->name('article-category.subcategories');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('article-category', 'ArticleCategoryController');
    });

    Route::group(['middleware' => ['permission:article-manage-categories']], function () {
        //
        Route::get('article-category/subcategories/{category}', 'ArticleCategoryController@listSubcategories')->name('article-category.subcategories');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('article-category', 'ArticleCategoryController');
    });

    Route::group(['middleware' => ['permission:translation-manage-translations']], function () {

        // Route to translation manager interface : /translations
        // The middleware to control translation manager is written in app/config/translation-manager.php
        // Refer github  https://github.com/barryvdh/laravel-translation-manager

    });
    Route::group(['middleware' => ['permission:media-manage-media']], function () {
//        ctf0\MediaManager\MediaRoutes::routes();
    });
//    ctf0\MediaManager\MediaRoutes::routes();


});

ctf0\MediaManager\MediaRoutes::routes();
//Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
//Route::resource('roles', 'RoleController');
////





// MediaManager

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //

    protected $fillable =
        [

            'title',
            'content',
            'status',
            'user_id',
            'created_at',
            'updated_at',
            'slug',
            'category_id'

        ];


    public function editors()
    {
        return $this->belongsToMany('App\ArticleUser', 'article_user', 'article_id', 'user_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(ArticleCategory::class);
    }



}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\ArticleCategory;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Stichoza\GoogleTranslate\GoogleTranslate;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
* //     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     *      * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */


    public function translate(Request $request){

        if(Session::has('locale')){
            $locale = Session::get('locale');
        }

      $phrase = "Hello";
      $outcome = GoogleTranslate::trans($phrase,'cn');

      $result =  "The source: ". $phrase . "<br>";
      $result .= "<div class='btn btn-danger'>The translated outocome in " . $locale . " : " . $outcome . "</div>";

        return view('articles.translation', ['result' => $result]);

    }

    public function filter(Request $request)
    {
//

        $articles = Article::where('id','!=','0')->get();
        $selected_category = ArticleCategory::find( $request->get('filter-category'));

        if($request->get('filter-category') == 0 && $request->get('filter-author') == 0 && $request->get('filter-password') == '') {
            $articles = Article::where('id','!=','0')->get();
        }

        if($request->get('filter-keywords')!= '') {
            $keywords = $request->get('filter-keywords');
            $articles = Article::where('title', 'LIKE','%'.$keywords .'%')->get();
            $selected_keywords = $request->get('filter-keywords');

        }
        if($request->get('filter-category') !=0){
            $articles = $articles->where('category_id', '=', $request->get('filter-category'));
            $selected_category = ArticleCategory::find( $request->get('filter-category'));

        }
        if($request->get('filter-author') != 0){
            $articles = $articles->where('author_id', '=' , $request->get('filter-author'));
                $selected_author = User::find($request->get('filter-author'));
        }
         if($request->get('filter-start-date')){
                $articles = $articles->where('created_at', '>=', $request->get('filter-start-date').' 00:00:00');
                $selected_start_date = $request->get('filter-start-date');

        }
        if($request->get('filter-end-date')){
            $articles = $articles->where('created_at', '<=' , $request->get('filter-end-date'). '23:59:59');
            $selected_end_date = $request->get('filter-end-date');
        }



        $author_collection = array();

        $category_collection = array();
        $articles_temp = Article::all();
        foreach($articles_temp as $article){
            if(!in_array($article->author->id, $author_collection)){
                array_push($author_collection, $article->author->id);
            }
            if(!in_array($article->category->id, $category_collection)){
                array_push($category_collection, $article->category->id);
            }
        }

        $authors = DB::table('users')
            ->whereIn('id', $author_collection)
            ->get();

        $categories = DB::table('article_categories')
            ->whereIn('id', $category_collection)
            ->get();

        return view('articles.index',
            ['articles'=> $articles,
                'categories' => $categories,
                'authors' => $authors,
                'selected_author' => $selected_author?? null,
                'selected_category' => $selected_category?? null,
                'selected_keywords' =>$selected_keywords??null,
                'selected_start_date' => $selected_start_date??null,
                'selected_end_date' => $selected_end_date??null
            ]);


//        $articles = Article::where('created_at', '>=' ,$start_date)->get();
//
    }


    public function index()
    {
        $articles = Article::all();
        $author_collection = array();
        $category_collection = array();
        $locale = ['language' => app()->getLocale()];

        foreach($articles as $article){

            if($article->author){
                if( !in_array($article->author->id, $author_collection)){
                    array_push($author_collection, $article->author->id);
            }
            }
            if($article->category){
                if(!$article->category && !in_array($article->category->id, $category_collection)){
                    array_push($category_collection, $article->category->id);
                }
            }

        }

        $authors = User::all()
                    ->whereIn('id', $author_collection);


        $categories = ArticleCategory::all()
            ->whereIn('id', $category_collection);


        return view('articles.index', ['articles' =>$articles, 'categories' => $categories, 'authors' => $authors,
         'selected_author' => $selected_author?? null,
                'selected_category' => $selected_category?? null,
            'selected_keywords' =>$selected_keywords??null,
            'selected_start_date' => $selected_start_date??null,
            'selected_end_date' => $selected_end_date??null
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $categories = ArticleCategory::all();

        return view('articles.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        // Validate posted form data
        $validated = $request->validate([
            'title' => 'required|string',
            'content' => 'required|string',
            'category' => 'required'
        ]);

        // Create slug from title
        $validated['slug'] = Str::slug($validated['title'], '-');
        $user = Auth::user();

        // Create and save post with validated data
//        $article = Article::create($validated);
        $article = new Article;
        $article->title = $validated['title'];
        $article->content = $validated['content'];
        $article->category_id = $validated['category'];
        $article->status = 1;
        $article->slug = Str::slug($validated['title'], '-');
        $article->author_id = $user->getAuthIdentifier();
        $article->save();

        // Redirect the user to the created post with a success notification
        $request->session()->flash('status-green', 'New article "' . $article->title . '" has been created.' );
        return redirect(route('articles.show', [$article->id]));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $article = Article::findOrFail($id);
        return view('articles.show', compact('article'));
//        return $article;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
//   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     *      * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $article = Article::find($id);
        $categories = ArticleCategory::all();

        return view('articles.edit', compact('article'), compact('categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $article = Article::find($id);

//        $article->save();
////        print_r($article);
        $validated = $request->validate([

            'title' => 'required|string',
            'content'  => 'string',
            'category' => 'required'
        ]);

//        // Create slug from title
//        $validated['slug'] = Str::slug($validated['title'], '-');
//
//        // Update Post with validated data
//        $article->update($validated);
//        $article->title = $validated['title'];

        if($request->publish==1){
            $article->status = $request->publish;
            $article->save();
        }

        $article->update(
            ['title' => $validated['title'],
                'content' => $validated['content'],
                'category' => $validated['category']
            ]
        );

//
//        // Redirect the user to the created post woth an updated notification
        $request->session()->flash('status-green', '"' . $article->title . '" has been updated.' );
        return redirect()->route('articles.show', ['article' => $article->id]);



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        //
        $article = Article::find($id);
        $article->delete();
        $request->session()->flash('status-red', '"' . $article->title . '" has been removed.' );
        return redirect(route('articles.index'));

    }

    public function changeStatus(Request $request, $id)
    {
        $article = Article::find($id);
        if($article->status == 1)
        {
            $article->status = 0;
            $request->session()->flash('status-yellow', '"' . $article->title . '" has been unpublished. It is now saved to draft.' );
        }
        else{
            $article->status = 1;
            $request->session()->flash('status-green', '"' . $article->title . '" has been published' );

        }

resources/views/articles/categories/category-treeview-secondary.blade.php
@foreach($subcategories as $subcategory)



    <ul >
        <li>
            <a href="{{ route('article-category.edit', [$subcategory->id])}}" class="btn btn-light">{{$subcategory->title}}</a>
        </li>
        @if(count($subcategory->subcategory))
            @include('articles.categories.category-treeview-secondary',['subcategories' => $subcategory->subcategory])

        @endif
    </ul>

@endforeach

resources/views/articles/categories/category-treeview.blade.php
@extends('layouts.app')


@section('content')
    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif
    <div class="container">
        {{--        <div class="row justify-content-center">--}}

        <div class="">
            <div class="card">
                <div class="card-header">
                    Article Categories(Tree mode)
                    <a href="{{ route('article-category.create') }}" class="float-right btn btn-success btn-space">Create a category</a>
                    <a href="{{ route('article-category.index') }}" class="float-right btn btn-outline-dark btn-space">Article Category List</a>
                </div>

                <div>
                        @foreach ($parents as $category)
                                    <a href="{{ route('article-category.edit', [$category->id])}}" class="btn btn-light">{{$category->title}}</a>
                            @if(count($category->subcategory))
                                @include('articles.categories.category-treeview-secondary',['subcategories' => $category->subcategory])
                            @endif

                        @endforeach
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/articles/categories/create.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="title">Create a new category</h1>

    <form method="post" action="{{ route('article-category.store') }}">

        @csrf

        @include('partials.errors')
        <div class="field">
            <label class="label">Category Title</label>
            <div class="control">
                <input type="text" name="title" value="{{ old('title') }}" class="input" placeholder="Title" maxlength="100" required />
            </div>
            <label class="label">Category Slug</label>
            <div class="control">
                <input type="text" name="slug" value="{{ old('slug') }}" class="input" placeholder="slug" maxlength="100" required />
            </div>
        </div>

        <div class="field">
            <label class="label">Category Description</label>

            <textarea class="form-control" id="" name="description"></textarea>
            <!-- The toolbar will be rendered in this container. -->
            <div id="toolbar-container"></div>
        </div>

        <div class="field">
            <label class="label">Parent Category</label>
            <div class="control">
                <div class="select">
                    <select name="parent-category" >
                        <option value="" disabled hidden selected>Select category</option>
                        <option value="0">No Parent Category</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}" >{{$category->title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

{{--        <div class="field">--}}
{{--            <label class="label">Category</label>--}}
{{--            <div class="control">--}}
{{--                <div class="select">--}}
{{--                    <select name="category" required>--}}
{{--                        <option value="" disabled selected>Select category</option>--}}
{{--                        <option value="Education" {{ old('category') === 'Education' ? 'selected' : null }}>Education</option>--}}
{{--                        <option value="Business" {{ old('category') === 'Business' ? 'selected' : null }}>Business</option>--}}
{{--                        <option value="Entertainment" {{ old('category') === 'Entertainment' ? 'selected' : null }}>Entertainment</option>--}}
{{--                        <option value="Sports" {{ old('category') === 'Sports' ? 'selected' : null }}>Sports</option>--}}
{{--                        <option value="Relationship" {{ old('category') === 'Relationship' ? 'selected' : null }}>Relationship</option>--}}
{{--                    </select>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}

        <br>
        <div class="field">
            <div class="control">
                <button type="submit" class="button is-link is-outlined">Create</button>
                <a href="{{ route('article-category.index')}}" class="btn btn-outline-primary btn-space">Return to Category List</a>
            </div>
        </div>

    </form>

@endsection

resources/views/articles/categories/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="title">Edit category</h1>

    <form method="post" action="{{ route('article-category.update', [$current_category->id]) }}">

        @csrf
        @method('patch')
        @include('partials.errors')

        @include('partials.errors')
        <div class="field">
            <label class="label">Category Title</label>
            <div class="control">
                <input type="text" name="title" value="{{ $current_category->title}}" class="input" placeholder="Title" minlength="5" maxlength="100" required />
            </div>
            <label class="label">Category Slug</label>
            <div class="control">
                <input type="text" name="slug" value="{{ $current_category->slug}}" class="input" placeholder="slug" maxlength="100" required />
            </div>
        </div>

        {{--        <div class="field">--}}
        {{--            <label class="label">Category Title</label>--}}
        {{--            <div class="control">--}}
        {{--                <input type="textarea" name="title" value="{{ old('description') }}" class="input" placeholder="Description" required />--}}
        {{--            </div>--}}
        {{--        </div>--}}


        <div class="field">
            <label class="label">Category Description</label>

            <textarea class="form-control" id="" name="description">{{$current_category->description}}</textarea>
            <!-- The toolbar will be rendered in this container. -->
            <div id="toolbar-container"></div>
        </div>

        <hr>
        <div class="field">
            <label class="label">Parent Category</label>
            <div class="control">
                <div class="select">
                    <select name="parent-category">
                        <option value="0">No Parent Category</option>
                        @foreach($categories as $category)
                            @if($current_category->upper_level !=0)
                                <option value="{{$current_category->parent->id}}" selected hidden>{{$current_category->parent->title}}</option>
                            @endif
                                <option value="{{$category->id}}" >{{$category->title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>

        </div>



        <br>
        <div class="field">
            <div class="control">
                <button type="submit" class="btn btn-outline-primary btn-space">Edit</button>
                <a href="{{route('article-category.index')}}" class="btn btn-outline-primary btn-space">Return to Article Categories</a>

            </div>
        </div>

    </form>


@endsection

resources/views/articles/categories/index.blade.php
@extends('layouts.app')


@section('content')
    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif
<div class="container">
    {{--        <div class="row justify-content-center">--}}

    <div class="">
        <div class="card">
            <div class="card-header">
                Article Categories
                <a href="{{ route('article-category.create') }}" class="float-right btn btn-success btn-space" >Create a category</a>
                <a href="{{ route('articles.index') }}" class="float-right btn btn-outline-dark btn-space">Article List</a>
                <a href="{{ route('article-category.subcategories', 0) }}" class="float-right btn btn-outline-dark btn-space">View in Tree Mode</a>
            </div>

            <div>
                <table class="article-category-list">
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Slug</th>
                        <th>Description</th>
                        <th>Parent Categories</th>

                    </tr>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{$category->id}}</td>
{{--                            <td>{{}}</td>--}}
                            <td>{{$category->title}}</td>
                            <td>{{$category->slug}}</td>
                            <td>{{$category->description}}</td>
                            <td>{{$category->parent? $category->parent->title : "-" }}</td>
                            @if(count($category->subcategory)>0)
                            <td><a href="{{ route('article-category.subcategories', [$category->id])}}" class="btn btn-outline-primary btn-space">Subcategories</a></td>
{{--                            <td><a href="{{ route('article-category.subcategories', [$category->id])}}" class="btn btn-outline-primary btn-space">{{count($category->subcategory)}}</a></td>--}}
                            @else
                                <td><a href="{{ route('article-category.subcategories', [$category->id])}}" class="btn btn-outline-primary disabled btn-space">Subcategories</a></td>
                            @endif
                                <td><a href="{{ route('article-category.edit', [$category->id])}}" class="btn btn-outline-primary btn-space">Edit</a></td>

                                <td>
                                <form method="post" action="{{ route('article-category.destroy', [$category->id]) }}">
                                    @csrf @method('delete')

                                    <div class="control">
                                        <button type="submit" class="btn btn-outline-danger btn-space" onclick="return confirm('Are you sure you want to delete this category?')">
                                            Delete
                                        </button>
                                    </div>

                                </form>

                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>

</div>

    @endsection