routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/testing', function(){

    return "This is a testing route";


});
Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
Route::resource('roles', 'RoleController');
Route::get('/exists/{file}' , function($file){

    if(Storage::disk('public')->exists('Basic/branch')){

        return "File exists";
    }
    else{
        return "No such file";
    }

});



Route::resource('participants', 'ParticipantController');

Route::get('/upload', 'UserController@uploadPhoto')->name('upload.image');
Route::post('/uploadResult', 'UserController@upload')->name('upload.result');


Route::get('locale/{locale}', function($locale){
            Session::put('locale', $locale);
            return redirect()->back();
})->name('locale');


Route::get('/home', 'HomeController@index')->name('home');



    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

Route::resource('users', 'UserController');


Route::group(['middleware' => ['auth']], function () {


    //

    Route::group(['middleware' => ['permission:user-manage-roles']], function () {
        //

//        Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
//        Route::resource('roles', 'RoleController');

    });

    Route::group(['middleware' => ['permission:user-manage-users']], function () {


        //        Route::resource('users', 'UserController');

    });

    Route::group(['middleware' => ['permission:article-manage-articles']], function () {
        //
        Route::post('articles/image_upload', 'ArticleController@upload')->name('upload');
        Route::get('articles/translate', 'ArticleController@translate')->name('translate');
        Route::get('articles/filter', 'ArticleController@filter')->name('articles.filter');
        Route::get('articles/change-status/{article}', 'ArticleController@changeStatus')->name('articles.changestatus');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('articles', 'ArticleController');
    });

    Route::group(['middleware' => ['permission:article-manage-categories']], function () {
        //
        Route::get('article-category/subcategories/{category}', 'ArticleCategoryController@listSubcategories')->name('article-category.subcategories');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('article-category', 'ArticleCategoryController');
    });

    Route::group(['middleware' => ['permission:article-manage-categories']], function () {
        //
        Route::get('article-category/subcategories/{category}', 'ArticleCategoryController@listSubcategories')->name('article-category.subcategories');  //Always define the route for customised function of a resource controller before defining the resource controller.
        Route::resource('article-category', 'ArticleCategoryController');
    });

    Route::group(['middleware' => ['permission:translation-manage-translations']], function () {

        // Route to translation manager interface : /translations
        // The middleware to control translation manager is written in app/config/translation-manager.php
        // Refer github  https://github.com/barryvdh/laravel-translation-manager

    });
    Route::group(['middleware' => ['permission:media-manage-media']], function () {
//        ctf0\MediaManager\MediaRoutes::routes();
    });
//    ctf0\MediaManager\MediaRoutes::routes();


});

ctf0\MediaManager\MediaRoutes::routes();
//Route::post('/roles/new-role', 'RoleController@storeRole')->name('roles.store.role');
//Route::resource('roles', 'RoleController');
////





// MediaManager

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //

    protected $fillable =
        [

            'title',
            'content',
            'status',
            'user_id',
            'created_at',
            'updated_at',
            'slug',
            'category_id'

        ];


    public function editors()
    {
        return $this->belongsToMany('App\ArticleUser', 'article_user', 'article_id', 'user_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(ArticleCategory::class);
    }



}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\ArticleCategory;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Stichoza\GoogleTranslate\GoogleTranslate;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
* //     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     *      * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */


    public function translate(Request $request){

        if(Session::has('locale')){
            $locale = Session::get('locale');
        }

      $phrase = "Hello";
      $outcome = GoogleTranslate::trans($phrase,'cn');

      $result =  "The source: ". $phrase . "<br>";
      $result .= "<div class='btn btn-danger'>The translated outocome in " . $locale . " : " . $outcome . "</div>";

        return view('articles.translation', ['result' => $result]);

    }

    public function filter(Request $request)
    {
//

        $articles = Article::where('id','!=','0')->get();
        $selected_category = ArticleCategory::find( $request->get('filter-category'));

        if($request->get('filter-category') == 0 && $request->get('filter-author') == 0 && $request->get('filter-password') == '') {
            $articles = Article::where('id','!=','0')->get();
        }

        if($request->get('filter-keywords')!= '') {
            $keywords = $request->get('filter-keywords');
            $articles = Article::where('title', 'LIKE','%'.$keywords .'%')->get();
            $selected_keywords = $request->get('filter-keywords');

        }
        if($request->get('filter-category') !=0){
            $articles = $articles->where('category_id', '=', $request->get('filter-category'));
            $selected_category = ArticleCategory::find( $request->get('filter-category'));

        }
        if($request->get('filter-author') != 0){
            $articles = $articles->where('author_id', '=' , $request->get('filter-author'));
                $selected_author = User::find($request->get('filter-author'));
        }
         if($request->get('filter-start-date')){
                $articles = $articles->where('created_at', '>=', $request->get('filter-start-date').' 00:00:00');
                $selected_start_date = $request->get('filter-start-date');

        }
        if($request->get('filter-end-date')){
            $articles = $articles->where('created_at', '<=' , $request->get('filter-end-date'). '23:59:59');
            $selected_end_date = $request->get('filter-end-date');
        }



        $author_collection = array();

        $category_collection = array();
        $articles_temp = Article::all();
        foreach($articles_temp as $article){
            if(!in_array($article->author->id, $author_collection)){
                array_push($author_collection, $article->author->id);
            }
            if(!in_array($article->category->id, $category_collection)){
                array_push($category_collection, $article->category->id);
            }
        }

        $authors = DB::table('users')
            ->whereIn('id', $author_collection)
            ->get();

        $categories = DB::table('article_categories')
            ->whereIn('id', $category_collection)
            ->get();

        return view('articles.index',
            ['articles'=> $articles,
                'categories' => $categories,
                'authors' => $authors,
                'selected_author' => $selected_author?? null,
                'selected_category' => $selected_category?? null,
                'selected_keywords' =>$selected_keywords??null,
                'selected_start_date' => $selected_start_date??null,
                'selected_end_date' => $selected_end_date??null
            ]);


//        $articles = Article::where('created_at', '>=' ,$start_date)->get();
//
    }


    public function index()
    {
        $articles = Article::all();
        $author_collection = array();
        $category_collection = array();
        $locale = ['language' => app()->getLocale()];

        foreach($articles as $article){

            if($article->author){
                if( !in_array($article->author->id, $author_collection)){
                    array_push($author_collection, $article->author->id);
            }
            }
            if($article->category){
                if(!$article->category && !in_array($article->category->id, $category_collection)){
                    array_push($category_collection, $article->category->id);
                }
            }

        }

        $authors = User::all()
                    ->whereIn('id', $author_collection);


        $categories = ArticleCategory::all()
            ->whereIn('id', $category_collection);


        return view('articles.index', ['articles' =>$articles, 'categories' => $categories, 'authors' => $authors,
         'selected_author' => $selected_author?? null,
                'selected_category' => $selected_category?? null,
            'selected_keywords' =>$selected_keywords??null,
            'selected_start_date' => $selected_start_date??null,
            'selected_end_date' => $selected_end_date??null
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $categories = ArticleCategory::all();

        return view('articles.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        // Validate posted form data
        $validated = $request->validate([
            'title' => 'required|string',
            'content' => 'required|string',
            'category' => 'required'
        ]);

        // Create slug from title
        $validated['slug'] = Str::slug($validated['title'], '-');
        $user = Auth::user();

        // Create and save post with validated data
//        $article = Article::create($validated);
        $article = new Article;
        $article->title = $validated['title'];
        $article->content = $validated['content'];
        $article->category_id = $validated['category'];
        $article->status = 1;
        $article->slug = Str::slug($validated['title'], '-');
        $article->author_id = $user->getAuthIdentifier();
        $article->save();

        // Redirect the user to the created post with a success notification
        $request->session()->flash('status-green', 'New article "' . $article->title . '" has been created.' );
        return redirect(route('articles.show', [$article->id]));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $article = Article::findOrFail($id);
        return view('articles.show', compact('article'));
//        return $article;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
//   * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     *      * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $article = Article::find($id);
        $categories = ArticleCategory::all();

        return view('articles.edit', compact('article'), compact('categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $article = Article::find($id);

//        $article->save();
////        print_r($article);
        $validated = $request->validate([

            'title' => 'required|string',
            'content'  => 'string',
            'category' => 'required'
        ]);

//        // Create slug from title
//        $validated['slug'] = Str::slug($validated['title'], '-');
//
//        // Update Post with validated data
//        $article->update($validated);
//        $article->title = $validated['title'];

        if($request->publish==1){
            $article->status = $request->publish;
            $article->save();
        }

        $article->update(
            ['title' => $validated['title'],
                'content' => $validated['content'],
                'category' => $validated['category']
            ]
        );

//
//        // Redirect the user to the created post woth an updated notification
        $request->session()->flash('status-green', '"' . $article->title . '" has been updated.' );
        return redirect()->route('articles.show', ['article' => $article->id]);



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        //
        $article = Article::find($id);
        $article->delete();
        $request->session()->flash('status-red', '"' . $article->title . '" has been removed.' );
        return redirect(route('articles.index'));

    }

    public function changeStatus(Request $request, $id)
    {
        $article = Article::find($id);
        if($article->status == 1)
        {
            $article->status = 0;
            $request->session()->flash('status-yellow', '"' . $article->title . '" has been unpublished. It is now saved to draft.' );
        }
        else{
            $article->status = 1;
            $request->session()->flash('status-green', '"' . $article->title . '" has been published' );

        }

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="title">Create a new article</h1>

    <form method="post" action="{{ route('articles.store') }}">

        @csrf

        @include('partials.errors')
        <div class="field">
            <label class="label">Title</label>
            <div class="control">
                <input type="text" name="title" value="{{ old('title') }}" class="input" placeholder="Title"
                        required/>
            </div>
        </div>


        <div class="field">
            <label class="label">Content</label>

            <textarea class="form-control" id="summary-ckeditor" name="content"></textarea>

            <div id="toolbar-container"></div>


        </div>

        <div class="field">
            <label class="label">Category</label>
            <div class="control">
                <div class="select">
                    <select name="category" required>
                        <option value="" disabled selected>Select category</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <br>
        <div class="field">
            <div class="control">
                <button type="submit" class="btn btn-outline-primary">Publish</button>
                <a href="{{ route('articles.index')}}" class="btn btn-outline-primary btn-space">Return to Article List</a>

            </div>
        </div>

    </form>

@endsection

resources/views/articles/edit.blade.php
@section('title', 'Edit Article')
@section('action', route('articles.create'))
@extends('layouts.app')

@section('content')

    <h1 class="title">Edit: {{ $article->title }}</h1>

    <form method="post" action="{{ route('articles.update', [$article->id])}}">

        @csrf
        @method('patch')
        @include('partials.errors')

        <div class="field">
            <label class="label">Title</label>
            <div class="control">
                <input type="text" name="title" value="{{ $article->title }}" class="input" placeholder="Title"
                       minlength="5" maxlength="100" required/>
            </div>
        </div>

        <div class="field">
            <label class="label">Content</label>
            <div class="control">
                <textarea class="form-control" id="summary-ckeditor" name="content">{{$article->content}}</textarea>

            </div>
        </div>

        <div class="field">
            <label class="label">Category</label>
            <div class="control">
                <div class="select">
                    <select name="category" required>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <br>

        @if($article->status!=1)
            <input type="checkbox" id="publish" name="publish" value="1">
            <label for="publish">Publish this article once it is updated.</label>
        @endif
        <br>

        <div class="field">
            <span>
                <button type="submit" class="btn btn-outline-primary">Update</button></span>
            <span>
                <a href="{{ route('articles.index')}}" class="btn btn-outline-primary">Return to Article List</a>
            </span>
        </div>

    </form>



@endsection

resources/views/articles/editor.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Document editor</title>


</head>
<body>
<h1>Document editor</h1>

<!-- The toolbar will be rendered in this container. -->
<div id="toolbar-container"></div>

<div class="field">
    <label class="label">請在以下空白編輯文章</label>
    <textarea class="form-control" id="summary-ckeditor" name="content"></textarea>

    <!-- The toolbar will be rendered in this container. -->
    <div id="toolbar-container"></div>


</div>
<script src="{{ asset('ckeditor4/ckeditor.js') }}"></script>


<script>

    CKEDITOR.replace('summary-ckeditor', {
        filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form'
    });

    // ----------------------CKEDITOR 5.0---------------------------
    // DecoupledEditor
    //     .create( document.querySelector( '#editor' ),
    //
    //
    //     )
    //     .then( editor => {
    //         const toolbarContainer = document.querySelector( '#toolbar-container' );
    //
    //         toolbarContainer.appendChild( editor.ui.view.toolbar.element );
    //     } )
    //
    //     .catch( error => {
    //         console.error( error );
    //     } );
    //
    // DecoupledEditor.builtinPlugins.map( plugin => plugin.pluginName );

</script>
</body>
</html>

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')

    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif
    {{--    <br><br>--}}
    <div class="container">
        {{--        <div class="row justify-content-center">--}}

        <div class="">
            <div class="card">

                <div class="card-header">
                    Articles
                    <a href="{{ route('articles.create' )}}" class="float-right btn btn-success btn-space">Create an
                        article</a>
                    <a href="{{ route('article-category.index') }}" class="float-right btn btn-outline-dark btn-space">Manage
                        Categories</a>
                    <a href="{{ route('home') }}" class="float-right btn btn-outline-dark btn-space">Home</a>
                </div>

                <div class="card-header">

                    <form method="get" action="{{ route('articles.filter')}}">
                        <div class="form-group">


                            {{--                                    <label for="filter-start-date">From</label>--}}
                            <input type="date" name="filter-start-date" value="{{$selected_start_date}}">

                            <label for="filter-start-date">To</label>
                            <input type="date" name="filter-end-date" value="{{$selected_end_date}}">

                            <select name="filter-category" class="custom-select custom-select-md col-sm-2">

                                @if($selected_category)
                                    <option value="{{$selected_category->id}}" selected
                                            hidden>{{$selected_category->title}}</option>
                                @endif
                                <option value="0">All Categories</option>
                                @foreach($categories as $category)

                                    <option value="{{$category->id}}">{{$category->title}}</option>

                                @endforeach
                            </select>

                            <select name="filter-author" class="custom-select custom-select-md col-sm-2">
                                @if($selected_author)
                                    <option value="{{$selected_author->id}}" selected
                                            hidden>{{$selected_author->name}}</option>
                                @endif
                                <option value="0">All Authors</option>
                                @foreach($authors as $author)
                                    <option value="{{$author->id}}">{{$author->name}}</option>
                                @endforeach
                            </select>
                            @if($selected_keywords)
                                <input type="text" name="filter-keywords" placeholder="" value="{{$selected_keywords}}">
                            @else
                                <input type="text" name="filter-keywords" placeholder="Search keywords...">
                            @endif

                            <button type="submit" class="btn btn-space btn-outline-dark">Filter</button>
                            <a href="{{ route('articles.index') }}" class=" btn btn-outline-dark btn-space">Clear
                                Filter</a>
                        </div>


                    </form>


                    <div>
                        <div>


                        </div>
                        <table class="article-list">
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Author</th>
                                <th>Status</th>
                                <th>Created at</th>

                            </tr>
                            @foreach ($articles as $article)
                                <tr>
                                    <td>{{$article->id}}</td>
                                    <td>{{$article->title}}</td>
                                    {{--                                <td>{!! substr($article->content, 0, 30) . "..." !!} </td>--}}
                                    <td>{{$article->category->title}}</td>
                                    {{--                                <td>{{$article->category_id}}</td>--}}
                                    <td>{{$article->author->name}}</td>
                                    {{--                                <td>{{$article->author_id}}</td>--}}
                                    <td>{{$article->status==1? "Published" : "Draft"}}</td>
                                    <td>{{$article->created_at?  $article->created_at : "N/A"}}</td>
                                    {{--                                <td>{{$article->updated_at?  $article->updated_at->diffForHumans() : "N/A"}}</td>--}}
                                    <td><a href="{{ route('articles.show', [ 'article' => $article->id  ])}}"
                                           class="btn btn-outline-primary btn-space">Read</a></td>
                                    <td><a href="{{ route('articles.edit', [  'article' => $article->id])}}"
                                           class="btn btn-outline-primary btn-space">Edit</a></td>
                                    <td><a href="{{ route('articles.changestatus', [ 'article' => $article->id])}}"
                                           class="btn btn-outline-primary btn-space">{{$article->status==1? "Unpublish": "Publish"}}</a>
                                    </td>
                                    <td>
                                        <form method="post" action="{{ route('articles.destroy', [ 'article' => $article->id]) }}">
                                            @csrf @method('delete')

                                            <div class="control">
                                                <button type="submit" class="btn btn-outline-danger btn-space"
                                                        onclick="return confirm('Are you sure you want to delete this article?')">
                                                    Delete
                                                </button>
                                            </div>

                                        </form>

                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>

        </div>
@endsection

resources/views/articles/show.blade.php
@section('title', $article->title)
@extends('layouts.app')

@section('content')

    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif

    @include('partials.summary')

@endsection

resources/views/articles/translation.blade.php
@extends('layouts.app')

@section('content')

    @if (session('status-green'))
        <div class="alert alert-success">
            {{ session('status-green') }}
        </div>

    @elseif(session('status-red'))
        <div class="alert alert-danger">
            {{ session('status-red') }}
        </div>

    @elseif(session('status-yellow'))
        <div class="alert alert-warning">
            {{ session('status-yellow') }}
        </div>
    @endif
    {{--    <br><br>--}}
    <div class="container">
        {{--        <div class="row justify-content-center">--}}

        <div class="">
            <div class="card">

                <div class="card-header">
                    Articles
                    <a href="{{ route('articles.create' )}}" class="float-right btn btn-success btn-space">Create an
                        article</a>
                    <a href="{{ route('article-category.index') }}" class="float-right btn btn-outline-dark btn-space">Manage
                        Categories</a>
                    <a href="{{ route('home') }}" class="float-right btn btn-outline-dark btn-space">Home</a>
                </div>

                <div class="card-header">

                            {!!$result !!}

                    <div>
                        <div class="card-body">



                        </div>

                    </div>
                </div>
            </div>

        </div>
@endsection